# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      loglevels:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'log levels'
        default: 'warning'
        # Input has to be provided for the workflow to run
        required: true
      tags:
        description: 'Enter your test tag'
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Navigate to POM file and do the Build test
      run: | 
           cd mvn4CI
           mvn -B package --file pom.xml
           mvn clean test
